name: front_scaffold_flutter
description: FrontScaffoldFlutter es una plantilla robusta y flexible diseñada para acelerar el desarrollo de proyectos en Flutter. Esta plantilla proporciona una estructura organizada, componentes reutilizables y las mejores prácticas de codificación para garantizar un inicio rápido y un mantenimiento sin problemas. Es adecuada para una amplia variedad de aplicaciones, desde aplicaciones móviles simples hasta proyectos más complejos.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  dio: ^5.3.4
  device_preview: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^4.2.0
  flutter_local_notifications: ^16.2.0
  shared_preferences: ^2.2.2
  flutter_localization: ^0.1.14
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
  mockito: ^5.4.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.24.3

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
