name: recipe_finder
description: Explore and cook with Recipe Finder in Flutter. Search for recipes, save your favorites and enjoy cooking easily. Download now and cook in style!
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  dio: ^5.3.4
  device_preview: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^4.2.0
  flutter_local_notifications: ^16.2.0
  shared_preferences: ^2.2.2
  flutter_localization: ^0.1.14
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
  mockito: ^5.4.3
  flutter_animate: ^4.3.0
  gap: ^3.0.1
  flutter_dotenv: ^5.1.0
  infinite_scroll_pagination: ^4.0.0
  image_picker: ^1.0.5
  dotted_border: ^2.1.0
  flutter_typeahead: ^5.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/categories/
    - assets/images/
    - assets/logos/
    - assets/launcher/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 400
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat/Caveat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Caveat/Caveat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Caveat/Caveat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Caveat/Caveat-Bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
